### ISSUE TITLE
高频率调用invoke时会产生oom

### ISSUE THREAD

**Issue by sunclgogo** [jeremyczhen/fdbus#11]
hi jeremy @jeremyczhen 
在高频调用invoke时、FDB_CONTEXT线程会发生oom、请问这个问题跟最近修改的内存泄漏问题有关么？invoke使用的原型参照下面：
nvoke(FdbMsgCode_t code
                           , const CFdbBasePayload &data
                           , int32_t timeout)

**Comment by jeremyczhen** [comment]
能把你正在使用的commit号给我吗？

**Comment by sunclgogo** [comment]
@jeremyczhen commit应该是804ba7bf9cacdf882884d27d276b83123c5ed341、我们这用的比较早。
最近调查这个问题时发现、将invoke改成send后、问题好像得到改善、怀疑跟invoke的auto reply有关系、send好像没有auto reply的机制吧？

**Comment by jeremyczhen** [comment]
Issue is fixed. The root cause is: at server side, auto-reply will be sent if message is not manually replied in onInvoke() to cancel pending request at client side. But in some cases auto reply does not take effect, leading to accumulation of pending request, eventually OOM.

@sunclgogo Please find branch hotfix_autoreply_for_sunclgogo for the fix-up. It is based on 804ba7bf9cacdf882884d27d276b83123c5ed341.

**Comment by sunclgogo** [comment]
@jeremyczhen well noted, thanks for your quick turnaround to fix the issue。
